name: Continuous Integration

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npx panva/npm-install-retry
      - run: npm run format-check
      - run: ./examples/.update-diffs.mjs
      - run: git diff --quiet

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          check-latest: true
      - name: Install dependencies
        run: npx panva/npm-install-retry
      - name: Test
        run: npm run test
