name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * 1-5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - run: npm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - run: npm run format-check
      - run: ./examples/.update-diffs.sh
      - run: git diff --quiet

  node:
    runs-on: ubuntu-latest
    env:
      ESBK_DISABLE_CACHE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - name: Run Test Suite
        run: npm run tap:node
      - name: Run Network Tests
        run: npm run test

  edge-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - name: Run Test Suite
        run: npm run tap:edge-runtime

  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Test Deno Definitions
        run: deno check src/index.ts
      - name: Run Test Suite
        run: npm run tap:deno

  workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - name: Run Test Suite
        run: npm run tap:workers

  browsers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome:headless
          - firefox:headless
          - edge:headless
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - name: Run Test Suite
        run: npm run tap:browsers
        env:
          BROWSER: ${{ matrix.browser }}
