name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * 1-5

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - run: npm clean-install
      - run: npm run format-check
      - run: ./examples/.update-diffs.mjs
      - run: git diff --quiet

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm clean-install
      - run: npm run test

  deno:
    strategy:
      fail-fast: false
      matrix:
        deno-version:
          - v1.21.0
          - v1

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Definitions
        run: deno check src/index.ts
