name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
          check-latest: true
      - name: Install dependencies
        run: npx panva/npm-install-retry
      - name: Test
        run: npm run test
