name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * 1-5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - run: npm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - run: npm run format-check
      - run: ./examples/.update-diffs.sh
      - run: git diff --quiet

  node:
    runs-on: ubuntu-latest
    env:
      ESBK_DISABLE_CACHE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - run: npm run test
      - name: Run Universal Tests
        run: npm run tap:node

  edge-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'npm'
      - run: npm clean-install
      - name: Run Universal Tests
        run: npm run tap:edge-runtime | tee edge-runtime.tap
      - id: parse
        uses: Coderlane/tap-action@d5de2302c571f90ccb2d2e9416eaca4efe3185dd
      - if: ${{ steps.parse.outputs.tap_fail != '0' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('npm run tap:edge-runtime failed')

  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Test Deno Definitions
        run: deno check src/index.ts
      - name: Run Universal Tests
        run: npm run tap:deno
